import streamlit as st

# Configuración general
st.set_page_config(page_title="Stock y Pedidos Completo", layout="wide")
st.title("📦 STOCK Y PEDIDOS POR DÍA (EXACTO)")
st.caption("Datos tomados directamente de tu lista: 0 = no se pide ese día, puedes registrar tu stock igual")
st.markdown("---")

# Seleccionar día
dia = st.selectbox(
    "Elige el día",
    ["LUNES", "MARTES", "MIÉRCOLES", "JUEVES", "VIERNES", "SÁBADO"]
)
st.subheader(f"📋 Día: {dia}")
st.markdown("---")

# Colores
VERDE = ":green["
ROJO = ":red["
FIN = "]"

# Función para pedidos y stock
def controlar_producto(nombre, cantidad_pedir):
    stock_actual = st.number_input(f"{nombre}", min_value=0.0, value=0.0, step=0.5)
    
    if cantidad_pedir == 0:
        st.write(f"👉 Pedir: 0 | Tienes: {stock_actual} | **{VERDE}No se necesita pedir hoy, tienes {stock_actual} en stock{FIN}**")
    else:
        falta = cantidad_pedir - stock_actual
        if falta > 0:
            st.write(f"👉 Pedir: {cantidad_pedir} | Tienes: {stock_actual} | **FALTAN: {ROJO}{falta}{FIN}**")
        else:
            st.write(f"👉 Pedir: {cantidad_pedir} | Tienes: {stock_actual} | **COMPLETO: {VERDE}{abs(falta)} DE SOBRANTE{FIN}**")
    st.markdown("---")

# ==============================================
# DATOS EXACTOS DE TU LISTA CORREGIDA
# ==============================================
if dia == "LUNES":
    controlar_producto("Ají Catalán Dulce x kilo", 4)
    controlar_producto("Ají Catalán Picante x kilo", 0)
    controlar_producto("Anana Imp x unidad", 2)
    controlar_producto("Banana Brasil x kilo", 0)
    controlar_producto("Banana Ecuador x kilo", 6)
    controlar_producto("Berenjena x kilo", 26)
    controlar_producto("Boniato criollo mediano x kilo", 0)
    controlar_producto("Boniato Criollo x kilo", 14)
    controlar_producto("Boniato zanahoria mediano x kilo", 0)
    controlar_producto("Boniato zanahoria x kilo", 8)
    controlar_producto("Cebolla Especial x kilo", 18)
    controlar_producto("Cebolla roja x kilo", 0)
    controlar_producto("Cebolla segunda x kilo", 2)
    controlar_producto("Chaucha comun x kilo", 0)
    controlar_producto("Frutilla x kilo", 0)
    controlar_producto("Jengibre Imp x kilo", 22)
    controlar_producto("Kiwi Importado x kilo", 10)
    controlar_producto("Lima importada x kilo", 0)
    controlar_producto("Limón nacional x kilo", 36)
    controlar_producto("Limón x kilo Goddard", 2)
    controlar_producto("Mandarina Afurer x kilo", 0)
    controlar_producto("Mandarina Clementina x kilo", 60)
    controlar_producto("Mandarina Criolla x kilo", 10)
    controlar_producto("Mango importado x unidad (3u)", 2)
    controlar_producto("Manzana Crispin x kilo", 0)
    controlar_producto("Manzana Granny Smith x kilo", 4)
    controlar_producto("Manzana Red 2ª x kilo", 0)
    controlar_producto("Manzana Red x kilo", 20)
    controlar_producto("Morron Amarillo x kilo", 6)
    controlar_producto("Morron Rojo 2ª x Kilo", 0)
    controlar_producto("Morron Rojo x Kilo", 38)
    controlar_producto("Morron Verde x kilo", 36)
    controlar_producto("Naranja esp x kilo", 42)
    controlar_producto("Naranja Navel 2da x kilo", 0)
    controlar_producto("Papa Blanca Especial x kilo", 6)
    controlar_producto("Papa Rosada Esp premium x kilo", 10)
    controlar_producto("Papaya importada x kilo (3u)", 0)
    controlar_producto("Pepino x kilo", 22)
    controlar_producto("Pera Francesa x kilo", 22)
    controlar_producto("Pera x kilo Goddard", 0)
    controlar_producto("Platano importado x kilo", 2)
    controlar_producto("Pomelo rosado x kilo", 0)
    controlar_producto("Sandia importada x kilo", 44)
    controlar_producto("Tomate americano x kilo", 0)
    controlar_producto("Tomate Cherry Redondo x kilo", 4)
    controlar_producto("Tomate Esp Sur larga vida x kilo", 26)
    controlar_producto("Tomate perita x kilo", 0)
    controlar_producto("Tomate x kilo Goddard", 13)
    controlar_producto("Zanahoria x kilo", 38)
    controlar_producto("Zapallito x kilo", 8)

elif dia == "MARTES":
    controlar_producto("Ají Catalán Dulce x kilo", 0)
    controlar_producto("Ají Catalán Picante x kilo", 6)
    controlar_producto("Anana Imp x unidad", 4)
    controlar_producto("Banana Brasil x kilo", 0)
    controlar_producto("Banana Ecuador x kilo", 30)
    controlar_producto("Berenjena x kilo", 24)
    controlar_producto("Boniato criollo mediano x kilo", 0)
    controlar_producto("Boniato Criollo x kilo", 36)
    controlar_producto("Boniato zanahoria mediano x kilo", 0)
    controlar_producto("Boniato zanahoria x kilo", 34)
    controlar_producto("Cebolla Especial x kilo", 30)
    controlar_producto("Cebolla roja x kilo", 4)
    controlar_producto("Cebolla segunda x kilo", 0)
    controlar_producto("Chaucha comun x kilo", 6)
    controlar_producto("Frutilla x kilo", 0)
    controlar_producto("Jengibre Imp x kilo", 12)
    controlar_producto("Kiwi Importado x kilo", 6)
    controlar_producto("Lima importada x kilo", 0)
    controlar_producto("Limón nacional x kilo", 14)
    controlar_producto("Limón x kilo Goddard", 0)
    controlar_producto("Mandarina Afurer x kilo", 0)
    controlar_producto("Mandarina Clementina x kilo", 46)
    controlar_producto("Mandarina Criolla x kilo", 30)
    controlar_producto("Mango importado x unidad (3u)", 4)
    controlar_producto("Manzana Crispin x kilo", 10)
    controlar_producto("Manzana Granny Smith x kilo", 4)
    controlar_producto("Manzana Red 2ª x kilo", 0)
    controlar_producto("Manzana Red x kilo", 20)
    controlar_producto("Morron Amarillo x kilo", 0)
    controlar_producto("Morron Rojo 2ª x Kilo", 0)
    controlar_producto("Morron Rojo x Kilo", 46)
    controlar_producto("Morron Verde x kilo", 34)
    controlar_producto("Naranja esp x kilo", 30)
    controlar_producto("Naranja Navel 2da x kilo", 0)
    controlar_producto("Papa Blanca Especial x kilo", 12)
    controlar_producto("Papa Rosada Esp premium x kilo", 12)
    controlar_producto("Papaya importada x kilo (3u)", 0)
    controlar_producto("Pepino x kilo", 4)
    controlar_producto("Pera Francesa x kilo", 6)
    controlar_producto("Pera x kilo Goddard", 0)
    controlar_producto("Platano importado x kilo", 0)
    controlar_producto("Pomelo rosado x kilo", 0)
    controlar_producto("Sandia importada x kilo", 0)
    controlar_producto("Tomate americano x kilo", 0)
    controlar_producto("Tomate Cherry Redondo x kilo", 0)
    controlar_producto("Tomate Esp Sur larga vida x kilo", 36)
    controlar_producto("Tomate perita x kilo", 0)
    controlar_producto("Tomate x kilo Goddard", 0)
    controlar_producto("Zanahoria x kilo", 38)
    controlar_producto("Zapallito x kilo", 38)

elif dia == "MIÉRCOLES":
    controlar_producto("Ají Catalán Dulce x kilo", 0)
    controlar_producto("Ají Catalán Picante x kilo", 6)
    controlar_producto("Anana Imp x unidad", 4)
    controlar_producto("Banana Brasil x kilo", 0)
    controlar_producto("Banana Ecuador x kilo", 18)
    controlar_producto("Berenjena x kilo", 38)
    controlar_producto("Boniato criollo mediano x kilo", 0)
    controlar_producto("Boniato Criollo x kilo", 18)
    controlar_producto("Boniato zanahoria mediano x kilo", 0)
    controlar_producto("Boniato zanahoria x kilo", 30)
    controlar_producto("Cebolla Especial x kilo", 12)
    controlar_producto("Cebolla roja x kilo", 0)
    controlar_producto("Cebolla segunda x kilo", 2)
    controlar_producto("Chaucha comun x kilo", 6)
    controlar_producto("Frutilla x kilo", 4)
    controlar_producto("Jengibre Imp x kilo", 16)
    controlar_producto("Kiwi Importado x kilo", 8)
    controlar_producto("Lima importada x kilo", 4)
    controlar_producto("Limón nacional x kilo", 28)
    controlar_producto("Limón x kilo Goddard", 0)
    controlar_producto("Mandarina Afurer x kilo", 66)
    controlar_producto("Mandarina Clementina x kilo", 0)
    controlar_producto("Mandarina Criolla x kilo", 10)
    controlar_producto("Mango importado x unidad (3u)", 15)
    controlar_producto("Manzana Crispin x kilo", 20)
    controlar_producto("Manzana Granny Smith x kilo", 4)
    controlar_producto("Manzana Red 2ª x kilo", 0)
    controlar_producto("Manzana Red x kilo", 8)
    controlar_producto("Morron Amarillo x kilo", 8)
    controlar_producto("Morron Rojo 2ª x Kilo", 0)
    controlar_producto("Morron Rojo x Kilo", 48)
    controlar_producto("Morron Verde x kilo", 50)
    controlar_producto("Naranja esp x kilo", 66)
    controlar_producto("Naranja Navel 2da x kilo", 0)
    controlar_producto("Papa Blanca Especial x kilo", 14)
    controlar_producto("Papa Rosada Esp premium x kilo", 10)
    controlar_producto("Papaya importada x kilo (3u)", 0)
    controlar_producto("Pepino x kilo", 6)
    controlar_producto("Pera Francesa x kilo", 28)
    controlar_producto("Pera x kilo Goddard", 0)
    controlar_producto("Platano importado x kilo", 0)
    controlar_producto("Pomelo rosado x kilo", 0)
    controlar_producto("Sandia importada x kilo", 0)
    controlar_producto("Tomate americano Redondo x kilo", 0)
    controlar_producto("Tomate Cherry Redondo x kilo", 0)
    controlar_producto("Tomate Esp Sur larga vida x kilo", 80)
    controlar_producto("Tomate perita x kilo", 6)
    controlar_producto("Tomate x kilo Goddard", 0)
    controlar_producto("Zanahoria x kilo", 22)
    controlar_producto("Zapallito x kilo", 24)

elif dia == "JUEVES":
    controlar_producto("Ají Catalán Dulce x kilo", 0)
    controlar_producto("Ají Catalán Picante x kilo", 0)
    controlar_producto("Anana Imp x unidad", 0)
    controlar_producto("Banana Brasil x kilo", 0)
    controlar_producto("Banana Ecuador x kilo", 0)
    controlar_producto("Berenjena x kilo", 12)
    controlar_producto("Boniato criollo mediano x kilo", 0)
    controlar_producto("Boniato Criollo x kilo", 20)
    controlar_producto("Boniato zanahoria mediano x kilo", 0)
    controlar_producto("Boniato zanahoria x kilo", 38)
    controlar_producto("Cebolla Especial x kilo", 11)
    controlar_producto("Cebolla roja x kilo", 8)
    controlar_producto("Cebolla segunda x kilo", 0)
    controlar_producto("Chaucha comun x kilo", 0)
    controlar_producto("Frutilla x kilo", 8)
    controlar_producto("Jengibre Imp x kilo", 12)
    controlar_producto("Kiwi Importado x kilo", 6)
    controlar_producto("Lima importada x kilo", 2)
    controlar_producto("Limón nacional x kilo", 50)
    controlar_producto("Limón x kilo Goddard", 0)
    controlar_producto("Mandarina Afurer x kilo", 56)
    controlar_producto("Mandarina Clementina x kilo", 0)
    controlar_producto("Mandarina Criolla x kilo", 10)
    controlar_producto("Mango importado x unidad (3u)", 0)
    controlar_producto("Manzana Crispin x kilo", 0)
    controlar_producto("Manzana Granny Smith x kilo", 6)
    controlar_producto("Manzana Red 2ª x kilo", 10)
    controlar_producto("Manzana Red x kilo", 0)
    controlar_producto("Morron Amarillo x kilo", 0)
    controlar_producto("Morron Rojo 2ª x Kilo", 0)
    controlar_producto("Morron Rojo x Kilo", 30)
    controlar_producto("Morron Verde x kilo", 18)
    controlar_producto("Naranja esp x kilo", 26)
    controlar_producto("Naranja Navel 2da x kilo", 0)
    controlar_producto("Papa Blanca Especial x kilo", 0)
    controlar_producto("Papa Rosada Esp premium x kilo", 0)
    controlar_producto("Papaya importada x kilo (3u)", 0)
    controlar_producto("Pepino x kilo", 0)
    controlar_producto("Pera Francesa x kilo", 6)
    controlar_producto("Pera x kilo Goddard", 0)
    controlar_producto("Platano importado x kilo", 0)
    controlar_producto("Pomelo rosado x kilo", 0)
    controlar_producto("Sandia importada x kilo", 18.5)
    controlar_producto("Tomate americano Redondo x kilo", 0)
    controlar_producto("Tomate Cherry Redondo x kilo", 0)
    controlar_producto("Tomate Esp Sur larga vida x kilo", 20)
    controlar_producto("Tomate perita x kilo", 0)
    controlar_producto("Tomate x kilo Goddard", 40)
    controlar_producto("Zanahoria x kilo", 42)
    controlar_producto("Zapallito x kilo", 0)

elif dia == "VIERNES":
    controlar_producto("Ají Catalán Dulce x kilo", 0)
    controlar_producto("Ají Catalán Picante x kilo", 0)
    controlar_producto("Anana Imp x unidad", 4)
    controlar_producto("Banana Brasil x kilo", 10)
    controlar_producto("Banana Ecuador x kilo", 10)
    controlar_producto("Berenjena x kilo", 10)
    controlar_producto("Boniato criollo mediano x kilo", 20)
    controlar_producto("Boniato Criollo x kilo", 20)
    controlar_producto("Boniato zanahoria mediano x kilo", 20)
    controlar_producto("Boniato zanahoria x kilo", 20)
    controlar_producto("Cebolla Especial x kilo", 20)
    controlar_producto("Cebolla roja x kilo", 18)
    controlar_producto("Cebolla segunda x kilo", 2)
    controlar_producto("Chaucha comun x kilo", 0)
    controlar_producto("Frutilla x kilo", 0)
    controlar_producto("Jengibre Imp x kilo", 20)
    controlar_producto("Kiwi Importado x kilo", 6)
    controlar_producto("Lima importada x kilo", 2)
    controlar_producto("Limón nacional x kilo", 26)
    controlar_producto("Limón x kilo Goddard", 0)
    controlar_producto("Mandarina Afurer x kilo", 50)
    controlar_producto("Mandarina Clementina x kilo", 0)
    controlar_producto("Mandarina Criolla x kilo", 0)
    controlar_producto("Mango importado x unidad (3u)", 0)
    controlar_producto("Manzana Crispin x kilo", 0)
    controlar_producto("Manzana Granny Smith x kilo", 0)
    controlar_producto("Manzana Red 2ª x kilo", 0)
    controlar_producto("Manzana Red x kilo", 4)
    controlar_producto("Morron Amarillo x kilo", 10)
    controlar_producto("Morron Rojo 2ª x Kilo", 6)
    controlar_producto("Morron Rojo x Kilo", 34)
    controlar_producto("Morron Verde x kilo", 22)
    controlar_producto("Naranja esp x kilo", 20)
    controlar_producto("Naranja Navel 2da x kilo", 0)
    controlar_producto("Papa Blanca Especial x kilo", 4)
    controlar_producto("Papa Rosada Esp premium x kilo", 12)
    controlar_producto("Papaya importada x kilo (3u)", 0)
    controlar_producto("Pepino x kilo", 14)
    controlar_producto("Pera Francesa x kilo", 8)
    controlar_producto("Pera x kilo Goddard", 0)
    controlar_producto("Platano importado x kilo", 0)
    controlar_producto("Pomelo rosado x kilo", 0)
    controlar_producto("Sandia importada x kilo", 0)
    controlar_producto("Tomate americano Redondo x kilo", 0)
    controlar_producto("Tomate Cherry Redondo x kilo", 0)
    controlar_producto("Tomate Esp Sur larga vida x kilo", 6)
    controlar_producto("Tomate perita x kilo", 0)
    controlar_producto("Tomate x kilo Goddard", 80)
    controlar_producto("Zanahoria x kilo", 20)
    controlar_producto("Zapallito x kilo", 22)

elif dia == "SÁBADO":
    controlar_producto("Ají Catalán Dulce x kilo", 0)
    controlar_producto("Ají Catalán Picante x kilo", 0)
    controlar_producto("Anana Imp x unidad", 2)
    controlar_producto("Banana Brasil x kilo", 20)
    controlar_producto("Banana Ecuador x kilo", 0)
    controlar_producto("Berenjena x kilo", 16)
    controlar_producto("Boniato criollo mediano x kilo", 0)
    controlar_producto("Boniato Criollo x kilo", 56)
    controlar_producto("Boniato zanahoria mediano x kilo", 0)
    controlar_producto("Boniato zanahori x kilo", 24)
    controlar_producto("Cebolla Especial x kilo", 22)
    controlar_producto("Cebolla roja x kilo", 10)
    controlar_producto("Cebolla segunda x kilo", 0)
    controlar_producto("Chaucha comun x kilo", 0)
    controlar_producto("Frutilla x kilo", 0)
    controlar_producto("Jengibre Imp x kilo", 16)
    controlar_producto("Kiwi Importado x kilo", 10)
    controlar_producto("Lima importada x kilo", 2)
    controlar_producto("Limón nacional x kilo", 6)
    controlar_producto("Limón x kilo Goddard", 0)
    controlar_producto("Mandarina Afurer x kilo", 40)
    controlar_producto("Mandarina Clementina x kilo", 0)
    controlar_producto("Mandarina Criolla x kilo", 20)
    controlar_producto("Mango importado x unidad (3u)", 3)
    controlar_producto("Manzana Crispin x kilo", 0)
    controlar_producto("Manzana Granny Smith x kilo", 0)
    controlar_producto("Manzana Red 2ª x kilo", 0)
    controlar_producto("Manzana Red x kilo", 0)
    controlar_producto("Morron Amarillo x kilo", 0)
    controlar_producto("Morron Rojo 2ª x Kilo", 0)
    controlar_producto("Morron Rojo x Kilo", 46)
    controlar_producto("Morron Verde x kilo", 40)
    controlar_producto("Naranja esp x kilo", 26)
    controlar_producto("Naranja Navel 2da x kilo", 10)
    controlar_producto("Papa Blanca Especial x kilo", 0)
    controlar_producto("Papa Rosada Esp premium x kilo", 22)
    controlar_producto("Papaya importada x kilo (3u)", 2)
    controlar_producto("Pepino x kilo", 10)
    controlar_producto("Pera Francesa x kilo", 0)
    controlar_producto("Pera x kilo Goddard", 20)
    controlar_producto("Platano importado x kilo", 4)
    controlar_producto("Pomelo rosado x kilo", 2)
    controlar_producto("Sandia importada x kilo", 0)
    controlar_producto("Tomate americano Redondo x kilo", 6)
    controlar_producto("Tomate Cherry Redondo x kilo", 0)
    controlar_producto("Tomate Esp Sur larga vida x kilo", 12)
    controlar_producto("Tomate perita x kilo", 0)
    controlar_producto("Tomate x kilo Goddard", 120)
    controlar_producto("Zanahoria x kilo", 34)
    controlar_producto("Zapallito x kilo", 74)
    # ... resto igual
